<?php

namespace Database\Seeders;

use App\Models\permissions;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * php artisan db:seed --class=RolePermissionSeeder
     *
     * @return void
     */
    public function run()
    {
        $dataJson = [
            "is_employee"=>"1",
            "is_age_of_employee"=>"1",
            "is_birthday_reminder"=>"1",
            "is_total_number_of_staff"=>"1",
            "is_total_inactive_staff"=>"1",
            "is_resigned_staff"=>"1",
            "is_reasons_of_staff"=>"1",
            "is_staff_ratio"=>"1",
            "is_staff_taking_leave"=>"1",
            "is_staff_training_internal"=>"1",
            "is_staff_training_external"=>"1"
        ];
        $datas = [
            [
                "name"=>"Dashboard",
                "is_dashboard" => json_encode($dataJson),
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Dashboards",
                "parent_id" => "1",
                "is_active" => 1,
                "table_id" => "1",
            ],
            [
                "name" => "All Employee",
                "table_id" => "3",
                "is_view" => "1",
                "is_create" => "1",
                "is_import" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_cancel" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Leaves Employee",
                "is_view" => "1",
                "is_create" => "1",
                "is_import" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_cancel" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Employee",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Candidate CV",
                "table_id" => "8",
                "is_view" => "1",
                "is_create" => "1",
                "is_import" => "1",
                "is_update" => "1",
                "is_approve" => "1",
                "is_delete" => "1",
                "is_cancel" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Recruitment Plan",
                "table_id" => "7",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "recruitments",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Payroll",
                "table_id" => "4",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_approve" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "nssf",
                "table_id" => "4",
                "is_view" => "1",
                "is_import" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Severance Pay",
                "table_id" => "4",
                "is_view" => "1",
                "is_import" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Fringe Benefits",
                "table_id" => "4",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_import" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Compensation and Benefits",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Motor Rental",
                "table_id" => "5",
                "is_view" => "1",
                "is_create" => "1",
                "is_import" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Pay Motor Rental",
                "table_id" => "6",
                "is_view" => "1",
                "is_create" => "1",
                "is_approve" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Motor Rentals",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Trainer",
                "table_id" => "10",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Training",
                "table_id" => "10",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Training Report",
                "table_id" => "10",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Trainings",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Employee Reports",
                "table_id" => "17",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Payroll Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Tax Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "NSSF Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Khm Pchum Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Severance Pay Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Seniorities Pay Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Fringe Benefits Reports",
                "table_id" => "18",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Bank Transfer Reports",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "E-Filing Reports",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "E-Form Reports",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Motor Rental Reports",
                "table_id" => "19",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "New Staff Reports",
                "table_id" => "20",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Staff Resigned Reports",
                "table_id" => "21",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Transferred Staff Reports",
                "table_id" => "23",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Promoted Staff Reports",
                "table_id" => "22",
                "is_view" => "1",
                "is_print" => "1",
                "is_export" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "reports",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Tax",
                "table_id" => "24",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Exchange Rate",
                "table_id" => "25",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Public Holidays",
                "table_id" => "12",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Children Allowance",
                "table_id" => "26",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Configuration",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Bank",
                "table_id" => "13",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Position",
                "table_id" => "15",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Branch",
                "table_id" => "16",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Department",
                "table_id" => "14",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "name" => "Forgot Password",
                "is_view" => "1",
                "is_create" => "1",
                "is_update" => "1",
                "is_delete" => "1",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            [
                "is_all" => "1",
                "name" => "Setting",
                "parent_id" => "1",
                "is_active" => 1,
            ],
            
        ];
        $roles=Role::get();
        foreach ($roles as $key=> $role) {
            if ($role->role_type == "developer") {
                $datas[] = [
                        "name" => "Role Permission",
                        "is_view" => "1",
                        "is_create" => "1",
                        "is_update" => "1",
                        "is_delete" => "1",
                        "is_print" => "1",
                        "is_export" => "1",
                        "parent_id" => "1",
                        "is_active" => 1,
                ];
                $datas[] =  [
                        "is_all" => "1",
                        "name" => "Role",
                        "parent_id" => "1",
                        "is_active" => 1,
                        "table_id" => "6",
                ];
            }
            foreach ($datas as $key => $item) {
                $item["role_id"] = $role->id;
                permissions::firstOrCreate($item);
            }
        };
       
    }
}
